### ISSUE TITLE
Support the `value` parameter for `constant_keyword` fields

### ISSUE THREAD

**Issue by ebeahan** [elastic/ecs#1052]
The [`constant_keyword` data type](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html#constant-keyword-field-type) accepts the `value` parameter. On a `constant_keyword` field if the `value` parameter is specified, that value is used for all documents in the index. Otherwise, it is set based on the first document that gets indexed.

If a user wishes to use the ECS tooling to manage their ES index templates, they may also wish to control the value of `value` via their custom field definitions.

Example definition:

```yaml
  - name: acme
    title: acme
    group: 2
    short: Fields describing acme-related needs.
    description: >
      Acme-related needs
    fields:
      - name: stream
        description: stream
        level: extended
        type: constant_keyword
        value: widgets
```
