### ISSUE TITLE
Support for `nested` data type fields

### ISSUE THREAD

**Issue by ebeahan** [elastic/ecs#1225]
Add support for the [`nested`](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html) data type in the ECS field definitions, artifacts, and docs.

**Requirements**

- [x] Fields using `nested` will need to define the properties of the nested documents.

Example:

```
- name: overlay
  type: nested
  fields:
    - name: chi2
      description: >
        Chi2 information of the PE file.
      type: float
    - name: entropy
      description: >
        Entropy information of the PE file.
      type: keyword
...
```
- [x] Generated artifacts will also need to contain the nested field's mapping under `properties`.

Example ES index template snippet:

```
"overlay": {
  "type": "nested",
   "properties": {
     "chi2": {
       "type": "float"
      },
      "entropy": {
        "ignore_above": 1024,
         "type": "keyword"
      },
...
```

- [x] The ECS documentation will need a clear, concise presentation format for the nested object mappings of a nested type field.

**Comment by ebeahan** [comment]
After some thought and experimentation using `type: nested,` I'm leaving some notes of my findings with the field definitions, artifacts, and documentation.

### Schema definitions

A nested field can be defined using an existing pattern seen in `dns.answers`. Definitions for `nested` fields would be structured the same with the parent level using `type: nested`:

```yaml
    - name: parent
      type: nested
      description: >
        ...
      normalize:
        - array
        
   - name: parent.child_one
      type: keyword
      ...

  - name: parent.child_two
    type: date
```

### Build

The only change I found that was required for the generator to generate artifacts successfully and docs running `make` is adding the `nested` type for the go code generated. 

PR opened to add https://github.com/elastic/ecs/pull/1254

### Artifacts

#### Composable index templates

Generated a `nested` mapping with no changes required.

```json
         {
          "properties": {
            "parent": {
              "properties": {
                "child_one": {
                  "ignore_above": 1024,
                  "type": "keyword"
                },
                "child_two": {
                  "type": "date"
                }
              },
              "type": "nested"
            }
          }
        }
```

#### Legacy index templates

Generated a `nested` mapping with no changes:

```json
      {
          "properties": {
            "parent": {
              "properties": {
                "child_one": {
                  "ignore_above": 1024,
                  "type": "keyword"
                },
                "child_two": {
                  "type": "date"
                }
              },
              "type": "nested"
            }
          }
        }
```

#### Beats field mappings

Again, no changes required with `type: nested`

```yaml
    fields:
    - name: parent
      level: extended
      type: nested
      description: parent
      default_field: false
    - name: parent.child_one
      level: extended
      type: keyword
      ignore_above: 1024
      description: First child field
      example: first
      default_field: false
    - name: parent.child_two
      level: extended
      type: date
      description: Second child field
      example: '2020-11-05T17:25:47.000Z'
      default_field: false
```

### Docs

I had considered and then experimented with adding a `nested parent` field to any field child of a nested parent field. I opted not to for two reasons:

1. The term `nesting` is already used in the documentation describing field reuse (e.g., `The user fields are expected to be nested at: ...`). I felt introducing a `nested parent` field and overloading the concept a bit introduces confusion.
2. There wasn't a clean way to add the `nested parent` information in `Field Reuse` section if field reuses are part of the nested child fields.

Instead, the parent field's description field can capture that the field is of `type: nested,` and any field under that field's namespace will fall into that nested structure. Again, this is similar to how `dns.answers` captures an array of objects.
