### ISSUE TITLE
Support for `nested` data type fields

### ISSUE THREAD

**Issue by ebeahan** [elastic/ecs#1226]
Add support for the [`nested`](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html) data type in the ECS field definitions, artifacts, and docs.

**Requirements**

- [ ] Fields using `nested` will need to define the properties of the nested documents.

Example:

```
- name: overlay
  type: nested
  fields:
    - name: chi2
      description: >
        Chi2 information of the PE file.
      type: float
    - name: entropy
      description: >
        Entropy information of the PE file.
      type: keyword
...
```
- [ ] Generated artifacts will also need to contain the nested field's mapping under `properties`.

Example ES index template snippet:

```
"overlay": {
  "type": "nested",
   "properties": {
     "chi2": {
       "type": "float"
      },
      "entropy": {
        "ignore_above": 1024,
         "type": "keyword"
      },
...
```

- [ ] The ECS documentation will need a clear, concise presentation format for the nested object mappings of a nested type field.
