### ISSUE TITLE
Allow nesting cloud under source, destination, server, and client

### ISSUE THREAD

**Issue by andrewthad** [elastic/ecs#1464]
**Summary**

Allow nesting `cloud` under `source`/`destination`/`server`/`client`.

**Motivation**:

A product that I work on enriches firewall logs by using the AWS and Azure lists of what public IP addresses are for what services (it also tells you what region they are in). Currently, there is no natural place for this information. Used at the top level, `cloud` implies that the log is about a host in a particular cloud. It is not appropriate for firewall logs at the top level. I want to be able to use `destination.cloud.region` and `destination.cloud.service.name`, but I currently cannot.

**Comment by ebeahan** [comment]
Do you mean defining those field reuses in the schema or allowing the `cloud` fieldset to be nested as custom fields?

The latter can be done using the `--include` flag and the `reusable.expected` attribute in a custom field definitions file. The custom attributes will merge with the fields defined in `schemas/cloud.yml`. 

`python scripts/generator.py --include <path>`

Example custom definition file `cloud_reuses.yml`. Using uppercase `Cloud` to align with ECS custom field best practices.

```yaml
---
- name: cloud
  reusable:
    expected:
      - at: source
        as: Cloud
      - at: destination
        as: Cloud
      - at: client
        as: Cloud
      - at: server
        as: Cloud
```
