### ISSUE TITLE
Extend Vulnerability Fieldset

### ISSUE THREAD

**Issue by jamiehynds** [elastic/ecs#1685]
Based on user feedback, we're missing some fields in our ECS vulnerability fields and suggest the following additions. 

- Mitigations and Solutions
  - This is another freetext field that explains to users how to fix or mitigate the problem
  - vulnerability.mitigation?
  
- CWE
  - This should be an array to help future proof itself. There are reasons to use multiple CWE names. Right now the ECS definition of reference is a string, an array should be considered. 
 
- id
  - We specify one id in ECS, which makes sense, but it's common for a CVE ID to also be mapped to various scanner IDs, I need another field, maybe alternate_id or secondary_id
 
- statement
  - This is different than the description. There are some CVE IDs that we will want to publish details about that include a statement such as "This library is not exposed to the external network in the container image"
  
- status
  - This is part of the statement data, so something could be a false positive, or future update, or whatever. It can have multiple statuses (is statuses a word?). For example something can be a false positive and also be getting a future update.

- vulnerability.status: Opened/Fixed/Ignored...
- vulnerability.patch: vulnerability.patch.exist (isFixable?, ), vulnerability.patch.code (ESA-2020-13), <div class="rfBrowextIocHighlightLink" key="vulnerability.patch.name" link="https://app.recordedfuture.com/live/sc/entity/idn:vulnerability.patch.name" style=""><span class="rfBrowextIocHighlightLink__title">vulnerability.patch.name</span></div>, ...
- Dates: vulnerability.discovered (first time detected), vulnerability.disclosed, vulnerability.closed, ..
- Affected components: link to CPE ?
- Decomposition of vulnerability.score.temporal to include exploitability. It could be interesting to automatically calculate it based on entered elements, and share the script.
- Ownership ? Might be through another field like service
- `vulnerability.category` [discussion](https://github.com/elastic/seceng/issues/1814#issuecomment-731236868)

**Comment by jamiehynds** [comment]
FYI @clement-fouque

**Comment by clement-fouque** [comment]
Thanks @jamiehynds. Here are some comments on the properties you were mentioning:
- `Mitigations and Solutions`
  - Pretty useful to store resolution from the scanner vendor or document mitigation in place
- `CWE`
  - Might be good to have an array of items with properties `name`, `id` & `description`
  - Details can be found here https://nvd.nist.gov/vuln/categories
- `id`
  -  A vulnerability doesn't have necessary a CVE associated with it. I don't know if it makes sense to seperate vulnerability ID (like CVEs) to the vendor/detection IDs. Using alternate_id or secondary_id might be good option.
- `status`
  - Values could also be: false_positive, risk_accepted, reopened, ...
- `patch`
  - I really like the idea to have 3 properties associated (exists, code and name) as it'll be easier to exclude vulnerabilities that have no patch and also group remediation by patch
- `dates`
  - I would also add last time found. 
- Affected components
  - Yep, CPE will probably be the way to go
- Decomposition of vulnerability.score.temporal to include exploitability
  - Excellent idea to have a script and share it. We can also extend it to `vulnerability.score.environmental`
  - It could give ideas/exemple to implement [First EPSS scoring](https://www.first.org/epss/).
- Ownership
  - As you said, it might not be the best place to store it. Having guidance where to store it would definitely help.  

I would also add
- `title` or `short description` as it's easier to use in dashboards
- Exploitability
  - CVSS is the prioritisation model that is the most often used. More mature vulnerability management program will use exploitability (end then environmental). 
  - It does not necessarly fit in `vulnerability.temporal` as we need to describe if exploit exists, maturity, last time it was found, ...
  - We might just adapt the `threat` field
- Severity which could be based on [First Qualitative Severity Rating Scale](https://www.first.org/cvss/specification-document) 

The following are ideas that might not be interesting to add in ECS:
- Scan details
  - Timing (Start/stop)
  - Method (IP/agent based) 
- Asset type
  - VM
  - Web
  - Container

**Comment by Apocrathia** [comment]
In addition to CPE, should a vulnerability be attributed to a specific asset? This way an individual host or resource can be queried for, and any related vulnerabilities can be attributed to the asset. It may also be useful to include CVSS environmental requirements to host fields for more robust CVSS calculations. I'm guessing something like this:
```yaml
host:
  name: example.local
  security:
    cpe:
      - cpe:/o:example:example:1.0
    requirements:
      - confidentiality: high
      - integrity: medium
      - availability: low
vulnerabiility:
  id: CVE-2019-11478
  report_id: 201701018.0001
  affected_components:
    - hostname: example.local
    - cpe: cpe:/o:example:example:1.0
 ```
By calling out specific assets in the vulnerability, you can better build a map of where issues are. I want to try and use Elastic as the tracking engine for my vulnerability management, and I may be misunderstanding something, so please correct me if necessary.

Alternatively, the `event` field could probably be used to build correlations between a `host` and `vulnerability` document. This would keep fields more consistent with their context and might be a better option. Consider the following:
```yaml
host:
  name: example.local
  security:
    cpe:
      - cpe:/o:example:example:1.0
    requirements:
      - confidentiality: high
      - integrity: medium
      - availability: low
event:
  id: random-id
  kind: alert
  category: 
    - vulnerability
  type: 
    - indicator
  provider:
    vulnerabiility:
      id: CVE-2019-11478
      report_id: 20171018.0001
  target:
    host:
      name: example.local
vulnerabiility:
  id: CVE-2019-11478
  report_id: 201701018.0001
  affected_components:
    - cpe: cpe:/o:example:example:1.0
```
Leveraging the event field to build these correlations might provide a more consistent way to add further information to vulnerability without modifications that could result in scope creep. By using the `event.provider` field, you can determine where the vulnerability information came from, and an `event.target` field could be used to generically reference whatever resource the event is attributed to. The only issue I see with the CPE field would be the generic nature of it, and that it doesn't target a specific asset, only a common platform. However, I agree that it is the correct attribute for the vulnerability field itself.

I guess the best question would be what use cases you guys have in mind for this extension so we can start to build an RFC.
