### ISSUE TITLE
Ability to add multi-field /subfield to all fields or fields of specified type

### ISSUE THREAD

**Issue by weslambert** [elastic/ecs#1819]
**Summary**

If I have a mutli-field/subfield  and an analyzer I would like applied to a particular multi-field/subfield, I would like to be able to have it automatically generated in the resultant artifacts, as opposed to having to manually edit or copy all existing mappings, and modify to include the subfield for every field.

For example, if I have .blah, that I want as type `text` and use `myspecialanalyzer` for every field, I would like to be able to specify it as an additional item to be considered when generating the mapping.  Each key could then be iterated over, and the 
mutli-field value appended to the existing list of multi-fields, or a multi-field set generated and the value populated.

**Motivation**:

Not having to manually modify mappings to add a multi-field/subfield to many different fields at once.

**Comment by kgeller** [comment]
Hi @weslambert !

This functionality was recently [implemented](https://github.com/elastic/ecs/pull/1737) as a result of an [issue](https://github.com/elastic/ecs/issues/1264). Thanks for bringing to my attention the need to document this capability :) 

You should be able to do something like the following 

```
- name: example
  title: example
  description: My example description.
  type: group
  fields:
  - name: field
    level: extended
    type: keyword
    multi_fields:
    - name: text
      type: text
      analyzer: my_custom_analyzer
    description: My field's description.
```

and then the generated artifacts will attach that field. The only thing you'll need to do manually is add the definition of your analyzer.
