### ISSUE TITLE
Standardize defining expected field values

### ISSUE THREAD

**Issue by ebeahan** [elastic/ecs#1951]
### Description

Create a new field attribute, `expected_values`, to capture recommended values for a given field.

Downstream schema consumers can validate integrations and mapped data against the `expected_values`. How expected values appear in the ECS field reference will also be standardized.

### Sample usage

```yaml
---
- name: faas
  fields:
    - name: trigger.type
      level: extended
      type: keyword
      short: The trigger for the function execution.
      expected_values:
        - http
        - pubsub
        - data source
        - timer
        - other
      description: >
        The trigger for the function execution.
```
