### ISSUE TITLE
subset.yml doesn't work for reuse fields unless "*" is used

### ISSUE THREAD

**Issue by maihde** [elastic/ecs#2024]
**Description of the problem including expected versus actual behavior**:

If you want to use a subset of a field set (i.e. `source.address` and `source.geo` but nothing else) the generator will fail with a ValueError in `extract_matching_fields`

**Steps to reproduce**:

1. Create a `subset.yml`  and generate a schema with it
```
name: mysubset
fields:
  source:
   fields:
     "address": {}
     "geo": {}
```

**Comment by kgeller** [comment]
Hi @maihde ! 

I was able to reproduce what you're seeing. However, I think the issues come down to a misunderstanding in how to use the subset file. I was able to get it working with a couple tweaks:

```
---
name: mysubset
fields:
  base:
    fields: "*"
  source:
    fields:
      geo: 
        fields: "*"
      address: {}
```

1) the field names won't be in quotes
2) in order to utilize just a field, like `source.address`, you'll want to use the `{}`, but in order to utilize a nested fieldset like `source.geo`, you'll want to add in that `fields: "*"`

Since I believe that covers it, I'm going to close this out for now. But if you find anything else, feel free to re-open or ask on the forum.
