### ISSUE TITLE
Unambigious ECS field: `client.domain

### ISSUE THREAD

**Issue by janstarke** [elastic/ecs#2119]
**Description of the issue:**
the `client` structure in `client.yml` describes the field `domain` twice

**Any additional context or examples:**
```yml
    - name: domain
      level: core
      type: keyword
      description: >
        Client domain.

    - name: domain
      level: core
      type: keyword
      short: The domain name of the client.
      example: foo.example.com
      description: >
        The domain name of the client system.

        This value may be a host name, a fully qualified domain name, or another
        host naming format. The value may derive from the original event or be
        added from enrichment.
```
