### ISSUE TITLE
Generator does not respect the parameter include_in_parent for nested fields

### ISSUE THREAD

**Issue by brett-fitz** [elastic/ecs#2148]
**Description of the issue:**

`Generator` tool does not respect the parameter `include_in_parent` for `nested` fields. There is also a chance I am not defining this correctly but the documentation is not clear on the use of this:

**Any additional context or examples:**

ECS Schema for field
```yaml
    - name: myfield
      level: custom
      type: nested
      description: > 
        An array of dictionaries description.
      short: myfield short description
      include_in_parent: True
      normalize:
        - array
```

ECS Composable Template generated:
```json
{
...
    "myfield": {
        "properties": { ... },
        "type": "nested"
    }
...
}
```
