### ISSUE TITLE
Allow use of dash character (`-`) in `data_stream.namespace`

### ISSUE THREAD

**Issue by ebeahan** [elastic/ecs#2388]
**Summary**

Propose ECS removes the restriction of using the dash character, `-`, in the `data_stream.namespace` field.

**Motivation**:

[RFC 0009 - Data stream fields](https://github.com/elastic/ecs/blob/main/rfcs/text/0009-data_stream-fields.md#restrictions-on-values) includes this restrictions for the `data_stream.namespace` field:

```
No longer than 100 chars
```

The [current description](https://github.com/elastic/ecs/blob/main/schemas/data_stream.yml#L69) for `data_stream.namespace` also restricts using the dash character:

```yaml
    - name: namespace
      level: extended
      type: constant_keyword
      example: production
      description: >
        A user defined namespace. Namespaces are useful to allow grouping of data.

        Many users already organize their indices this way, and the data stream naming scheme now provides this
        best practice as a default. Many users will populate this field with `default`. If no value is used, it falls back to `default`.

        Beyond the Elasticsearch index naming criteria noted above, `namespace` value has the additional restrictions:
          * Must not contain `-` <= Not present in RFC
          * No longer than 100 characters
      short: A user defined namespace. Namespaces are useful to allow grouping of data.
```

Suspect these restrictions may have been mistakenly copied from the same restriction on `data_stream.type` and `data_stream.dataset`.

I would not consider the change breaking. It makes `data_stream.namespace` more permissive and the `data_stream.*` field set is still considered beta.
