### ISSUE TITLE
Reusable fields with two or more prefixes

### ISSUE THREAD

**Issue by pedroSBastos** [elastic/ecs#410]
Why reusable fields can't be expected as nested when you have two prefixes or more?

For example:
```yaml
---
- name: example
  title: Example
  group: 2
  type: group
  description: >
    Example
  reusable:
    top_level: false
    expected:
      - first.second
      - first.second.third
```

The fields of this schema should be nested at: first.second.example and first.second.third.example
