### ISSUE TITLE
ECS Reusable objects? What about file.*

### ISSUE THREAD

**Issue by willemdh** [elastic/ecs#427]
We had a discussion about reusable fields lately and I was wondering why for example `file.*` is not marked as resuable. 

This while I can find the field `log.file.path` in multiple filebeat datasets?

`log.file.path` also doesn't seem to exist in https://github.com/elastic/ecs/blob/master/generated/csv/fields.csv ?

For example for `geo.*` I can find:
https://github.com/elastic/ecs/blob/master/schemas/geo.yml
```
  reusable:
    top_level: false
    expected:
      - client
      - destination
      - observer
      - host
      - server
      - source
```

So why not for `file.*` ?
https://github.com/elastic/ecs/blob/master/schemas/file.yml
 Is this on Elastic's to do or is `file.*` not meant to be reusable?
