### ISSUE TITLE
Mapping issue with source field when used with Filebeat custom input

### ISSUE THREAD

**Issue by willemdh** [elastic/ecs#69]
Hello,

Similar issue to tha one I had with the Logstash udp input adding host field. FIlebeat seems to add a source field by default when using a custom prospector / input.

For example:

```
filebeat.inputs:
- paths: ["/usr/local/nagiosxi/var/components/auditlog.log"]
  ignore_older: 3h
  fields_under_root: true
  fields.dig.app.name: "Nagios XI"
  fields.dig.app.type: "Audit Logs"
  pipeline: "filebeat-nagios-audit"
  processors:
    - drop_event:
        when.not.regexp:
          message: '^\d{4}.*'
```

Results in:

org.elasticsearch.index.mapper.MapperParsingException: object mapping for [source] tried to parse field [source] as object, but found a concrete value

![image](https://user-images.githubusercontent.com/6462991/43800667-4e5425cc-9a91-11e8-988c-b10c25265358.png)

when using source.ip in the used ingest pipeline. Is this already a known issue?
