### ISSUE TITLE
[1.5] network.inner, observer.ingress and observer.egress object definitions

### ISSUE THREAD

**Issue by codebrain** [elastic/ecs#780]
The following new schema definitions in ECS 1.5:

- `network.inner`
- `observer.ingress`
- `observer.egress`

Exhibit the same format of definition in the `ecs_nested.yml` file as:

- `dns.anwers`
- `log.syslog`

That is, they specify the root object and then subsequent properties off of this root object, for example (truncated YAML sample):

```
ingress:
      dashed_name: observer-ingress
      description: Observer.ingress holds information like interface number and name,
        vlan, and zone information to  classify ingress traffic.  Single armed monitoring
        such as a network sensor on a span port should  only use observer.ingress
        to categorize traffic.
      type: object
ingress.interface.alias:
      dashed_name: observer-ingress-interface-alias
      description: Interface alias as reported by the system, typically used in firewall
        implementations for e.g. inside, outside, or dmz logical interface naming.
      type: keyword
ingress.interface.id:
      dashed_name: observer-ingress-interface-id
      description: Interface ID as reported by an observer (typically SNMP interface
        ID).
      type: keyword
```

In C# it is not possible to have both a `class` and `property` with the same name, so in the ECS .NET generator we have adopted the same strategy for these new properties as `dns.answers` and `log.syslog`.

Does this seem reasonable?
